tap_install:
    sensitive_values:
        shared:
            ingress_domain: ENC[AES256_GCM,data:SEiFxrbW0m3Wlk4z0/Yiyt9/GT0/xj9Q4sB/8PmCibgS1CRrkCluCQ==,iv:kuebi3aaJLPEn+FPaoGekx84V8YC1MaDjttBSfb9w5c=,tag:eHPGj/lbnEwB9Fr3atcVyA==,type:str]
            ingress_issuer: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age140kfw9jqh7d63svrgf8rpjaf8mteg507va4s98pnjtl975qe6stqfpaxvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjanhwbThZUStqUzlQYUU3
            cURZeXo2eEFQSzF1N1V1NzdvcmNGeHNtTmhFClB6cGVjbFV1cjkzN3lkL0lvTFpQ
            YXliNFRXR0puVHNDMUtQc1NXa3FxVk0KLS0tIFZPL2QvSlphcTdsOUNFb1NXL0U4
            bGFxL3NVK2lneTJ4WXBsc1E5Z1pFaG8KOnzmcbCeYmDcABEXsuvwZFwxdi5euSM7
            KWi2wzNfB1XGc9RY7IqW3teX7rHa/tvYw8nSReySWC1WSHb/3XvLkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-23T09:42:33Z"
    mac: ENC[AES256_GCM,data:LBllB2FK8fvBWBS3dQV57LCfnylhG7fDjNEZRqYEZiFK8gfjBXUTuUHDPvlpQpV0y8jX18vNn9XR8GrydSMDp9eD4YnMbhXifadoZiBEIsUl4eM0lvSHb24jP1Udb+Bt18k7alR2MjJafHqgTGTgEE9ynzfc3RuEvWEX5QLFM9Q=,iv:Cu/kXKeFlILFmHREbAWHChNYqs01nbb1t6K7ZqQWUTg=,tag:nkgZU80FhcioWFjGcwOQBA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
